spring.application.name=studentMagement
spring.datasource.url=jdbc:postgresql://localhost:5432/student_management
spring.datasource.username=trinity
spring.datasource.password=PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081